# Read the Docs configuration file for Cookiecutter POC Template
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    # Generate example project before building docs
    pre_build:
      - bash docs/generate_example.sh
    post_build:
      - echo "Documentation built successfully!"

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Formats to build
formats:
  - pdf
  - epub
